apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    concurrency: 0
  artifacts:
    - image: hello-world
      bazel:
        target: //cmd:cmd.tar
deploy:
  kubectl: {}
# 로컬에서 쿠버네티스 사용 시 서비스에 노드 포트 혹은 노드 밸런스를 자동적으로 해주는 역할
portForward:
  - resourceType: deployment
    resourceName: hello-world
    port: 3000
    localPort: 3000
manifests:
  rawYaml:
    - hello_world.yaml